<a href="https://colab.research.google.com/github/krishnashashanth-sks/aiml-workspace/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas

In [ ]:
import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()
df.tail()
df.shape
pd.set_option("display.max_rows",500)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

### `pd.set_option` Function Explanation

The `pd.set_option` function in pandas is a powerful tool for controlling the global display and behavior of DataFrames and Series. It allows you to customize how pandas presents data, which can be invaluable during data exploration, debugging, and report generation.

Here's an advanced breakdown of its functionality:

### **1. Purpose**

`pd.set_option()` is used to modify pandas' global options. These options affect various aspects, including:

*   **Display options:** How many rows/columns are shown, floating-point precision, column width, etc.
*   **Behavioral options:** Warning suppression, performance-related settings.

### **2. Syntax**

The general syntax is `pd.set_option(key, value)`. The `key` is a string that specifies the option you want to change, and `value` is the new setting for that option.

### **3. Common and Advanced Options**

Pandas organizes its options into categories. Here are some of the most frequently used and advanced ones:

#### **a. Display Options (`display.*`)**

*   **`display.max_rows`**: Controls the maximum number of rows to display when printing a DataFrame. If there are more rows, only `max_rows` will be shown, along with an ellipsis.
    *   Example: `pd.set_option('display.max_rows', 500)`
    *   Advanced: Set to `None` to display all rows (use with caution on very large DataFrames: `pd.set_option('display.max_rows', None)`).

*   **`display.max_columns`**: Controls the maximum number of columns to display.
    *   Example: `pd.set_option('display.max_columns', 50)`
    *   Advanced: Set to `None` to display all columns: `pd.set_option('display.max_columns', None)`.

*   **`display.width`**: Sets the total width of the display in characters. This is often used in conjunction with `max_columns` to determine line wrapping.
    *   Example: `pd.set_option('display.width', 1000)`

*   **`display.precision`**: Sets the number of floating-point decimals to display for Series and DataFrames.
    *   Example: `pd.set_option('display.precision', 4)`

*   **`display.float_format`**: Allows for a custom formatter function for floating-point numbers. This is very powerful for consistent formatting.
    *   Example: `pd.set_option('display.float_format', lambda x: '%.3f' % x)` (formats floats to 3 decimal places)
    *   Advanced: Use `str.format` syntax for more complex formatting, e.g., `'{:.2f}%'.format`.

*   **`display.max_colwidth`**: Sets the maximum width of a column in characters. Text exceeding this width will be truncated.
    *   Example: `pd.set_option('display.max_colwidth', 100)`
    *   Advanced: Set to `None` to prevent truncation: `pd.set_option('display.max_colwidth', None)`.

*   **`display.colheader_justify`**: Justifies column headers ('left' or 'right').
    *   Example: `pd.set_option('display.colheader_justify', 'left')`

*   **`display.chop_threshold`**: For float values below this threshold, display as 0.
    *   Example: `pd.set_option('display.chop_threshold', 0.001)`

#### **b. Chaining Assignments (`mode.*`)**

*   **`mode.chained_assignment`**: Controls warnings related to chained assignment (e.g., `df['col'][row_indexer] = value`). Chained assignment can sometimes lead to unexpected results, and this option helps manage warnings.
    *   `'warn'` (default): Displays a `SettingWithCopyWarning`.
    *   `'raise'`: Raises an error.
    *   `None`: Suppresses the warning entirely.
    *   Example: `pd.set_option('mode.chained_assignment', None)` (to suppress the warning)

#### **c. Copy on Write (`mode.copy_on_write`)**

*   **`mode.copy_on_write`**: A newer option (introduced in pandas 2.0) that enables the Copy-on-Write optimization, which can improve performance and reduce memory usage by delaying data copying until absolutely necessary. When enabled, operations on views will create a copy only when a modification is attempted.
    *   `True` (enabled) or `False` (disabled).
    *   Example: `pd.set_option('mode.copy_on_write', True)`

#### **d. Other Useful Options**

*   **`io.excel.xls.writer` / `io.excel.xlsx.writer`**: Specify the default engine for writing Excel files.
    *   Example: `pd.set_option('io.excel.xlsx.writer', 'openpyxl')`

### **4. How to View Current Options**

You can view the current value of an option using `pd.get_option(key)`:

*   Example: `print(pd.get_option('display.max_rows'))`

To view all available options and their current values, you can use:

*   `pd.describe_option()`: Provides descriptions and current values for all options.
*   `pd.describe_option('display')`: Filters options by a keyword (e.g., 'display').

### **5. Resetting Options**

*   **Reset a specific option to its default**: You can get the default value using `pd.options.default_options[key]` (though this is more internal) or simply manually set it back.
*   **Reset all options to their defaults**: `pd.reset_option('all')`
    *   You can also reset specific categories, e.g., `pd.reset_option('display.max_rows')`.

### **6. Context Managers for Temporary Changes (`pd.option_context`)**

For temporary changes to options (e.g., within a specific function or block of code), it's highly recommended to use `pd.option_context` as a context manager. This ensures that the options are reset to their previous state after the block is exited, preventing global side effects.

*   Example:
    ```python
    with pd.option_context('display.max_rows', 10, 'display.precision', 2):
        display(my_dataframe) # my_dataframe will be displayed with 10 rows and 2 decimal places
    # After the 'with' block, display.max_rows and display.precision revert to their previous values.
    ```

### **7. Best Practices**

*   **Use `pd.set_option` sparingly for global changes**: Over-reliance on global settings can make code harder to understand and debug, as display behavior might be inconsistent across different parts of a project.
*   **Prefer `pd.option_context` for local changes**: This makes your code more robust and predictable.
*   **Be mindful of performance**: Setting `display.max_rows` or `display.max_columns` to `None` can consume significant memory and time for very large DataFrames, especially in interactive environments.

In [ ]:
df.index
df.columns
df.dtypes
df.info()
df.describe()
len(df)
max(df.index)
min(df.index)
type(df)
round(df,2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.49,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.82,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.65,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.19,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.92,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.36,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.52,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.03,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.98,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.01,94600.0

In [ ]:
df['households']
df['households'].index
df['households'].head()

0    472.0
1    463.0
2    117.0
3    226.0
4    262.0
Name: households, dtype: float64

In [ ]:
df.households
df[['households','latitude','longitude']]

       households  latitude  longitude
0           472.0     34.19    -114.31
1           463.0     34.40    -114.47
2           117.0     33.69    -114.56
3           226.0     33.64    -114.57
4           262.0     33.57    -114.57
...           ...       ...        ...
16995       369.0     40.58    -124.26
16996       465.0     40.69    -124.27
16997       456.0     41.84    -124.30
16998       478.0     41.80    -124.30
16999       270.0     40.54    -124.35

[17000 rows x 3 columns]

In [ ]:
df['sks']='SKS'
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'sks'],
      dtype='object')

# add new column with an array

In [ ]:
import numpy as np
sks=np.arange(0,17000)
df['sks']=sks
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,sks
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,1
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,2
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,4

In [ ]:
random_sks=np.random.randint(1,100,size=17000)
df['sks']=random_sks
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,sks
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,36
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,89
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,6
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,5
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,29

In [ ]:
np.random.uniform(1,100,size=10)

array([16.06133996, 65.68537941, 97.12102864, 93.8789163 ,  9.48385427,
       98.63871862, 88.23926128, 14.54710923, 86.65873421, 52.3148457 ])

In [ ]:
### assign
score1=np.random.randint(1,100,size=17000)
score2=np.random.randint(1,100,size=17000)
series1=pd.Series(score1,index=np.arange(0,17000))
series2=pd.Series(score2,index=np.arange(0,17000))
df=df.assign(score1=series1,score2=series2)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,sks,score1,score2
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,36,87,96
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,89,23,50
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,6,58,30
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,5,35,10
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,29,45,65

In [ ]:
# df.insert(1,'test',series1)
df

,longitude,test,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,sks,score1,score2
0,-114.31,87,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,36,87,96
1,-114.47,23,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,89,23,50
2,-114.56,58,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,6,58,30
3,-114.57,35,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,5,35,10
4,-114.57,45,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,29,45,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,80,40,80
16996,-124.27,27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,96,27,18
16997,-124.30,84,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,70,84,40
16998,-124.30,48,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,1,48,28
16999,-124.35,65,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,71,65,39

In [ ]:
# count method
df['households'].count()
df['households'].value_counts(normalize=True)

households
386.0     0.002824
306.0     0.002824
282.0     0.002765
330.0     0.002706
426.0     0.002647
            ...
1625.0    0.000059
908.0     0.000059
1903.0    0.000059
1288.0    0.000059
1646.0    0.000059
Name: proportion, Length: 1740, dtype: float64

In [ ]:
df.sort_values('households',ascending=False,inplace=False)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0
2871,-117.74,33.89,4.0,37937.0,5471.0,16122.0,5189.0,7.4947,366300.0
2969,-117.78,34.03,8.0,32054.0,5290.0,15507.0,5050.0,6.0191,253900.0
2274,-117.42,33.35,14.0,25135.0,4819.0,35682.0,4769.0,2.5729,134400.0
2086,-117.34,33.98,10.0,17286.0,4952.0,9851.0,4616.0,1.7579,103400.0
...,...,...,...,...,...,...,...,...,...
288,-116.76,34.14,4.0,42.0,10.0,9.0,3.0,0.5360,42500.0
15656,-122.37,37.60,26.0,15.0,3.0,11.0,3.0,5.0480,350000.0
2990,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.3750,137500.0
9670,-119.54,36.51,36.0,49.0,7.0,28.0,2.0,4.6250,162500.0
16309,-122.50,37.79,52.0,8.0,1.0,13.0,1.0,15.0001,500001.0

In [ ]:
#Create index
import random
import numpy as np
df=df[:100]
new_index=np.arange(0,100)
random.shuffle(new_index)
df['new_index']=new_index
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_index
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,54
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,73
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,21
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,76
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,53

In [ ]:
df.set_index('new_index')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
new_index,,,,,,,,,
63,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
72,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
29,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
17,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
94,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
15,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
28,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
35,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
69,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
19,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
64,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0
80,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0
54,-114.61,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0
85,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0
61,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0
8,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0
77,-114.65,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0
75,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0
55,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,44000.0
53,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0
83,-114.68,33.49,20.0,1491.0,360.0,1135.0,303.0,1.6395,44400.0
99,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0
14,-114.94,34.55,20.0,350.0,95.0,119.0,58.0,1.6250,50000.0
89,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0
25,-115.22,33.54,18.0,1706.0,397.0,3424.0,283.0,1.6250,53500.0
88,-115.32,32.82,34.0,591.0,139.0,327.0,89.0,3.6528,100000.0
60,-115.37,32.82,30.0,1602.0,322.0,1130.0,335.0,3.5735,71100.0
3,-115.37,32.82,14.0,1276.0,270.0,867.0,261.0,1.9375,80900.0
10,-115.37,32.81,32.0,741.0,191.0,623.0,169.0,1.7604,68600.0
9,-115.37,32.81,23.0,1458.0,294.0,866.0,275.0,2.3594,74300.0
46,-115.38,32.82,38.0,1892.0,394.0,1175.0,374.0,1.9939,65800.0
96,-115.38,32.81,35.0,1263.0,262.0,950.0,241.0,1.8958,67500.0
95,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0
65,-115.40,32.86,19.0,1087.0,171.0,649.0,173.0,3.3182,113800.0
86,-115.40,32.70,19.0,583.0,113.0,531.0,134.0,1.6838,95800.0
59,-115.41,32.99,29.0,1141.0,220.0,684.0,194.0,3.4038,107800.0
78,-115.46,33.19,33.0,1234.0,373.0,777.0,298.0,1.0000,40000.0
87,-115.48,32.80,21.0,1260.0,246.0,805.0,239.0,2.6172,88500.0
12,-115.48,32.68,15.0,3414.0,666.0,2097.0,622.0,2.3319,91200.0
38,-115.49,32.87,19.0,541.0,104.0,457.0,106.0,3.3583,102800.0
66,-115.49,32.69,17.0,1960.0,389.0,1691.0,356.0,1.8990,64000.0
84,-115.49,32.67,29.0,1523.0,440.0,1302.0,393.0,1.1311,84700.0
21,-115.49,32.67,25.0,2322.0,573.0,2185.0,602.0,1.3750,70100.0
7,-115.50,32.75,13.0,330.0,72.0,822.0,64.0,3.4107,142500.0
67,-115.50,32.68,18.0,3631.0,913.0,3565.0,924.0,1.5931,88400.0
41,-115.50,32.67,35.0,2159.0,492.0,1694.0,475.0,2.1776,75500.0
56,-115.51,33.24,32.0,1995.0,523.0,1069.0,410.0,1.6552,43300.0
43,-115.51,33.12,21.0,1024.0,218.0,890.0,232.0,2.1010,46700.0
27,-115.51,32.99,20.0,1402.0,287.0,1104.0,317.0,1.9088,63700.0
48,-115.51,32.68,11.0,2872.0,610.0,2644.0,581.0,2.6250,72700.0
18,-115.52,34.22,30.0,540.0,136.0,122.0,63.0,1.3333,42500.0
98,-115.52,33.13,18.0,1109.0,283.0,1006.0,253.0,2.1630,53400.0
50,-115.52,33.12,38.0,1327.0,262.0,784.0,231.0,1.8793,60800.0
57,-115.52,32.98,32.0,1615.0,382.0,1307.0,345.0,1.4583,58600.0
20,-115.52,32.97,24.0,1617.0,366.0,1416.0,401.0,1.9750,66400.0
23,-115.52,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0
76,-115.52,32.77,18.0,1715.0,337.0,1166.0,333.0,2.2417,79200.0
22,-115.52,32.73,17.0,1190.0,275.0,1113.0,258.0,2.3571,63100.0
2,-115.52,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0
33,-115.53,34.91,12.0,807.0,199.0,246.0,102.0,2.5391,40000.0
97,-115.53,32.99,25.0,2578.0,634.0,2082.0,565.0,1.7159,62200.0
4,-115.53,32.97,35.0,1583.0,340.0,933.0,318.0,2.4063,70700.0
81,-115.53,32.97,34.0,2231.0,545.0,1568.0,510.0,1.5217,60300.0
73,-115.53,32.73,14.0,1527.0,325.0,1453.0,332.0,1.7350,61200.0
26,-115.54,32.99,23.0,1459.0,373.0,1148.0,388.0,1.5372,69400.0
11,-115.54,32.99,17.0,1697.0,268.0,911.0,254.0,4.3523,96000.0
79,-115.54,32.98,27.0,1513.0,395.0,1121.0,381.0,1.9464,60600.0
36,-115.54,32.97,41.0,2429.0,454.0,1188.0,430.0,3.0091,70800.0
82,-115.54,32.79,23.0,1712.0,403.0,1370.0,377.0,1.2750,60400.0
6,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0
31,-115.55,32.98,24.0,2565.0,530.0,1447.0,473.0,3.2593,80800.0
30,-115.55,32.82,34.0,1540.0,316.0,1013.0,274.0,2.5664,67500.0
74,-115.55,32.80,23.0,666.0,142.0,580.0,160.0,2.1136,61000.0
5,-115.55,32.79,23.0,1004.0,221.0,697.0,201.0,1.6351,59600.0
47,-115.55,32.79,22.0,565.0,162.0,692.0,141.0,1.2083,53600.0
68,-115.55,32.78,5.0,2652.0,606.0,1767.0,536.0,2.8025,84300.0
32,-115.56,32.96,21.0,2164.0,480.0,1164.0,421.0,3.8177,107200.0
91,-115.56,32.80,28.0,1672.0,416.0,1335.0,397.0,1.5987,59400.0
45,-115.56,32.80,25.0,1311.0,375.0,1193.0,351.0,2.1979,63900.0
13,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0
1,-115.56,32.79,20.0,2372.0,835.0,2283.0,767.0,1.1707,62500.0
39,-115.56,32.79,18.0,1178.0,438.0,1377.0,429.0,1.3373,58300.0
24,-115.56,32.78,46.0,2511.0,490.0,1583.0,469.0,3.0603,70800.0
49,-115.56,32.78,35.0,1185.0,202.0,615.0,191.0,4.6154,86200.0
92,-115.56,32.78,29.0,1568.0,283.0,848.0,245.0,3.1597,76200.0
58,-115.56,32.76,15.0,1278.0,217.0,653.0,185.0,4.4821,140300.0
44,-115.57,32.85,33.0,1365.0,269.0,825.0,250.0,3.2396,62300.0
40,-115.57,32.85,17.0,1039.0,256.0,728.0,246.0,1.7411,63500.0
16,-115.57,32.84,29.0,1207.0,301.0,804.0,288.0,1.9531,61100.0
90,-115.57,32.83,31.0,1494.0,289.0,959.0,284.0,3.5282,67500.0
93,-115.57,32.80,16.0,2276.0,594.0,1184.0,513.0,1.8750,93800.0
71,-115.57,32.79,34.0,1152.0,208.0,621.0,208.0,3.6042,73600.0
37,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0
70,-115.57,32.78,15.0,1413.0,279.0,803.0,277.0,4.3021,87500.0
34,-115.58,33.88,21.0,1161.0,282.0,724.0,186.0,3.1827,71700.0
52,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0
0,-115.58,32.81,10.0,1088.0,203.0,533.0,201.0,3.6597,87500.0
62,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0
51,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0
42,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0

In [ ]:
#Sort index
df.sort_index()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_index
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,54
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,73
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,21
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,76
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,53
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0,49
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0,98
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0,85
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0,65
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0,33
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0,69
11,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0,31
12,-114.61,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0,91
13,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0,74
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0,60
15,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0,67
16,-114.65,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0,64
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0,5
18,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,44000.0,43
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0,9
20,-114.68,33.49,20.0,1491.0,360.0,1135.0,303.0,1.6395,44400.0,71
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0,34
22,-114.94,34.55,20.0,350.0,95.0,119.0,58.0,1.6250,50000.0,20
23,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0,16
24,-115.22,33.54,18.0,1706.0,397.0,3424.0,283.0,1.6250,53500.0,66
25,-115.32,32.82,34.0,591.0,139.0,327.0,89.0,3.6528,100000.0,77
26,-115.37,32.82,30.0,1602.0,322.0,1130.0,335.0,3.5735,71100.0,81
27,-115.37,32.82,14.0,1276.0,270.0,867.0,261.0,1.9375,80900.0,37
28,-115.37,32.81,32.0,741.0,191.0,623.0,169.0,1.7604,68600.0,61
29,-115.37,32.81,23.0,1458.0,294.0,866.0,275.0,2.3594,74300.0,58
30,-115.38,32.82,38.0,1892.0,394.0,1175.0,374.0,1.9939,65800.0,18
31,-115.38,32.81,35.0,1263.0,262.0,950.0,241.0,1.8958,67500.0,50
32,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0,70
33,-115.40,32.86,19.0,1087.0,171.0,649.0,173.0,3.3182,113800.0,10
34,-115.40,32.70,19.0,583.0,113.0,531.0,134.0,1.6838,95800.0,52
35,-115.41,32.99,29.0,1141.0,220.0,684.0,194.0,3.4038,107800.0,62
36,-115.46,33.19,33.0,1234.0,373.0,777.0,298.0,1.0000,40000.0,86
37,-115.48,32.80,21.0,1260.0,246.0,805.0,239.0,2.6172,88500.0,4
38,-115.48,32.68,15.0,3414.0,666.0,2097.0,622.0,2.3319,91200.0,48
39,-115.49,32.87,19.0,541.0,104.0,457.0,106.0,3.3583,102800.0,56
40,-115.49,32.69,17.0,1960.0,389.0,1691.0,356.0,1.8990,64000.0,28
41,-115.49,32.67,29.0,1523.0,440.0,1302.0,393.0,1.1311,84700.0,17
42,-115.49,32.67,25.0,2322.0,573.0,2185.0,602.0,1.3750,70100.0,12
43,-115.50,32.75,13.0,330.0,72.0,822.0,64.0,3.4107,142500.0,45
44,-115.50,32.68,18.0,3631.0,913.0,3565.0,924.0,1.5931,88400.0,83
45,-115.50,32.67,35.0,2159.0,492.0,1694.0,475.0,2.1776,75500.0,35
46,-115.51,33.24,32.0,1995.0,523.0,1069.0,410.0,1.6552,43300.0,42
47,-115.51,33.12,21.0,1024.0,218.0,890.0,232.0,2.1010,46700.0,40
48,-115.51,32.99,20.0,1402.0,287.0,1104.0,317.0,1.9088,63700.0,41
49,-115.51,32.68,11.0,2872.0,610.0,2644.0,581.0,2.6250,72700.0,3
50,-115.52,34.22,30.0,540.0,136.0,122.0,63.0,1.3333,42500.0,6
51,-115.52,33.13,18.0,1109.0,283.0,1006.0,253.0,2.1630,53400.0,1
52,-115.52,33.12,38.0,1327.0,262.0,784.0,231.0,1.8793,60800.0,75
53,-115.52,32.98,32.0,1615.0,382.0,1307.0,345.0,1.4583,58600.0,27
54,-115.52,32.97,24.0,1617.0,366.0,1416.0,401.0,1.9750,66400.0,38
55,-115.52,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0,84
56,-115.52,32.77,18.0,1715.0,337.0,1166.0,333.0,2.2417,79200.0,99
57,-115.52,32.73,17.0,1190.0,275.0,1113.0,258.0,2.3571,63100.0,97
58,-115.52,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0,14
59,-115.53,34.91,12.0,807.0,199.0,246.0,102.0,2.5391,40000.0,29
60,-115.53,32.99,25.0,2578.0,634.0,2082.0,565.0,1.7159,62200.0,82
61,-115.53,32.97,35.0,1583.0,340.0,933.0,318.0,2.4063,70700.0,0
62,-115.53,32.97,34.0,2231.0,545.0,1568.0,510.0,1.5217,60300.0,30
63,-115.53,32.73,14.0,1527.0,325.0,1453.0,332.0,1.7350,61200.0,7
64,-115.54,32.99,23.0,1459.0,373.0,1148.0,388.0,1.5372,69400.0,92
65,-115.54,32.99,17.0,1697.0,268.0,911.0,254.0,4.3523,96000.0,80
66,-115.54,32.98,27.0,1513.0,395.0,1121.0,381.0,1.9464,60600.0,25
67,-115.54,32.97,41.0,2429.0,454.0,1188.0,430.0,3.0091,70800.0,47
68,-115.54,32.79,23.0,1712.0,403.0,1370.0,377.0,1.2750,60400.0,95
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0,89
70,-115.55,32.98,24.0,2565.0,530.0,1447.0,473.0,3.2593,80800.0,24
71,-115.55,32.82,34.0,1540.0,316.0,1013.0,274.0,2.5664,67500.0,87
72,-115.55,32.80,23.0,666.0,142.0,580.0,160.0,2.1136,61000.0,96
73,-115.55,32.79,23.0,1004.0,221.0,697.0,201.0,1.6351,59600.0,90
74,-115.55,32.79,22.0,565.0,162.0,692.0,141.0,1.2083,53600.0,2
75,-115.55,32.78,5.0,2652.0,606.0,1767.0,536.0,2.8025,84300.0,8
76,-115.56,32.96,21.0,2164.0,480.0,1164.0,421.0,3.8177,107200.0,11
77,-115.56,32.80,28.0,1672.0,416.0,1335.0,397.0,1.5987,59400.0,22
78,-115.56,32.80,25.0,1311.0,375.0,1193.0,351.0,2.1979,63900.0,94
79,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0,93
80,-115.56,32.79,20.0,2372.0,835.0,2283.0,767.0,1.1707,62500.0,57
81,-115.56,32.79,18.0,1178.0,438.0,1377.0,429.0,1.3373,58300.0,13
82,-115.56,32.78,46.0,2511.0,490.0,1583.0,469.0,3.0603,70800.0,68
83,-115.56,32.78,35.0,1185.0,202.0,615.0,191.0,4.6154,86200.0,46
84,-115.56,32.78,29.0,1568.0,283.0,848.0,245.0,3.1597,76200.0,15
85,-115.56,32.76,15.0,1278.0,217.0,653.0,185.0,4.4821,140300.0,78
86,-115.57,32.85,33.0,1365.0,269.0,825.0,250.0,3.2396,62300.0,39
87,-115.57,32.85,17.0,1039.0,256.0,728.0,246.0,1.7411,63500.0,19
88,-115.57,32.84,29.0,1207.0,301.0,804.0,288.0,1.9531,61100.0,59
89,-115.57,32.83,31.0,1494.0,289.0,959.0,284.0,3.5282,67500.0,63
90,-115.57,32.80,16.0,2276.0,594.0,1184.0,513.0,1.8750,93800.0,44
91,-115.57,32.79,34.0,1152.0,208.0,621.0,208.0,3.6042,73600.0,23
92,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0,51
93,-115.57,32.78,15.0,1413.0,279.0,803.0,277.0,4.3021,87500.0,32
94,-115.58,33.88,21.0,1161.0,282.0,724.0,186.0,3.1827,71700.0,79
95,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0,72
96,-115.58,32.81,10.0,1088.0,203.0,533.0,201.0,3.6597,87500.0,88
97,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0,26
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0,55
99,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0,36

In [ ]:
#Rename column
df.rename(columns={'new_index':"NewIndex"})
df.rename(index={0:'A'})

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,new_index
A,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,54
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,73
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,21
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,76
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,53
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0,49
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0,98
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0,85
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0,65
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0,33
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0,69
11,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0,31
12,-114.61,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0,91
13,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0,74
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0,60
15,-114.65,34.89,17.0,2556.0,587.0,1005.0,401.0,1.6991,69100.0,67
16,-114.65,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0,64
17,-114.65,32.79,21.0,44.0,33.0,64.0,27.0,0.8571,25000.0,5
18,-114.66,32.74,17.0,1388.0,386.0,775.0,320.0,1.2049,44000.0,43
19,-114.67,33.92,17.0,97.0,24.0,29.0,15.0,1.2656,27500.0,9
20,-114.68,33.49,20.0,1491.0,360.0,1135.0,303.0,1.6395,44400.0,71
21,-114.73,33.43,24.0,796.0,243.0,227.0,139.0,0.8964,59200.0,34
22,-114.94,34.55,20.0,350.0,95.0,119.0,58.0,1.6250,50000.0,20
23,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0,16
24,-115.22,33.54,18.0,1706.0,397.0,3424.0,283.0,1.6250,53500.0,66
25,-115.32,32.82,34.0,591.0,139.0,327.0,89.0,3.6528,100000.0,77
26,-115.37,32.82,30.0,1602.0,322.0,1130.0,335.0,3.5735,71100.0,81
27,-115.37,32.82,14.0,1276.0,270.0,867.0,261.0,1.9375,80900.0,37
28,-115.37,32.81,32.0,741.0,191.0,623.0,169.0,1.7604,68600.0,61
29,-115.37,32.81,23.0,1458.0,294.0,866.0,275.0,2.3594,74300.0,58
30,-115.38,32.82,38.0,1892.0,394.0,1175.0,374.0,1.9939,65800.0,18
31,-115.38,32.81,35.0,1263.0,262.0,950.0,241.0,1.8958,67500.0,50
32,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0,70
33,-115.40,32.86,19.0,1087.0,171.0,649.0,173.0,3.3182,113800.0,10
34,-115.40,32.70,19.0,583.0,113.0,531.0,134.0,1.6838,95800.0,52
35,-115.41,32.99,29.0,1141.0,220.0,684.0,194.0,3.4038,107800.0,62
36,-115.46,33.19,33.0,1234.0,373.0,777.0,298.0,1.0000,40000.0,86
37,-115.48,32.80,21.0,1260.0,246.0,805.0,239.0,2.6172,88500.0,4
38,-115.48,32.68,15.0,3414.0,666.0,2097.0,622.0,2.3319,91200.0,48
39,-115.49,32.87,19.0,541.0,104.0,457.0,106.0,3.3583,102800.0,56
40,-115.49,32.69,17.0,1960.0,389.0,1691.0,356.0,1.8990,64000.0,28
41,-115.49,32.67,29.0,1523.0,440.0,1302.0,393.0,1.1311,84700.0,17
42,-115.49,32.67,25.0,2322.0,573.0,2185.0,602.0,1.3750,70100.0,12
43,-115.50,32.75,13.0,330.0,72.0,822.0,64.0,3.4107,142500.0,45
44,-115.50,32.68,18.0,3631.0,913.0,3565.0,924.0,1.5931,88400.0,83
45,-115.50,32.67,35.0,2159.0,492.0,1694.0,475.0,2.1776,75500.0,35
46,-115.51,33.24,32.0,1995.0,523.0,1069.0,410.0,1.6552,43300.0,42
47,-115.51,33.12,21.0,1024.0,218.0,890.0,232.0,2.1010,46700.0,40
48,-115.51,32.99,20.0,1402.0,287.0,1104.0,317.0,1.9088,63700.0,41
49,-115.51,32.68,11.0,2872.0,610.0,2644.0,581.0,2.6250,72700.0,3
50,-115.52,34.22,30.0,540.0,136.0,122.0,63.0,1.3333,42500.0,6
51,-115.52,33.13,18.0,1109.0,283.0,1006.0,253.0,2.1630,53400.0,1
52,-115.52,33.12,38.0,1327.0,262.0,784.0,231.0,1.8793,60800.0,75
53,-115.52,32.98,32.0,1615.0,382.0,1307.0,345.0,1.4583,58600.0,27
54,-115.52,32.97,24.0,1617.0,366.0,1416.0,401.0,1.9750,66400.0,38
55,-115.52,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0,84
56,-115.52,32.77,18.0,1715.0,337.0,1166.0,333.0,2.2417,79200.0,99
57,-115.52,32.73,17.0,1190.0,275.0,1113.0,258.0,2.3571,63100.0,97
58,-115.52,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0,14
59,-115.53,34.91,12.0,807.0,199.0,246.0,102.0,2.5391,40000.0,29
60,-115.53,32.99,25.0,2578.0,634.0,2082.0,565.0,1.7159,62200.0,82
61,-115.53,32.97,35.0,1583.0,340.0,933.0,318.0,2.4063,70700.0,0
62,-115.53,32.97,34.0,2231.0,545.0,1568.0,510.0,1.5217,60300.0,30
63,-115.53,32.73,14.0,1527.0,325.0,1453.0,332.0,1.7350,61200.0,7
64,-115.54,32.99,23.0,1459.0,373.0,1148.0,388.0,1.5372,69400.0,92
65,-115.54,32.99,17.0,1697.0,268.0,911.0,254.0,4.3523,96000.0,80
66,-115.54,32.98,27.0,1513.0,395.0,1121.0,381.0,1.9464,60600.0,25
67,-115.54,32.97,41.0,2429.0,454.0,1188.0,430.0,3.0091,70800.0,47
68,-115.54,32.79,23.0,1712.0,403.0,1370.0,377.0,1.2750,60400.0,95
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0,89
70,-115.55,32.98,24.0,2565.0,530.0,1447.0,473.0,3.2593,80800.0,24
71,-115.55,32.82,34.0,1540.0,316.0,1013.0,274.0,2.5664,67500.0,87
72,-115.55,32.80,23.0,666.0,142.0,580.0,160.0,2.1136,61000.0,96
73,-115.55,32.79,23.0,1004.0,221.0,697.0,201.0,1.6351,59600.0,90
74,-115.55,32.79,22.0,565.0,162.0,692.0,141.0,1.2083,53600.0,2
75,-115.55,32.78,5.0,2652.0,606.0,1767.0,536.0,2.8025,84300.0,8
76,-115.56,32.96,21.0,2164.0,480.0,1164.0,421.0,3.8177,107200.0,11
77,-115.56,32.80,28.0,1672.0,416.0,1335.0,397.0,1.5987,59400.0,22
78,-115.56,32.80,25.0,1311.0,375.0,1193.0,351.0,2.1979,63900.0,94
79,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0,93
80,-115.56,32.79,20.0,2372.0,835.0,2283.0,767.0,1.1707,62500.0,57
81,-115.56,32.79,18.0,1178.0,438.0,1377.0,429.0,1.3373,58300.0,13
82,-115.56,32.78,46.0,2511.0,490.0,1583.0,469.0,3.0603,70800.0,68
83,-115.56,32.78,35.0,1185.0,202.0,615.0,191.0,4.6154,86200.0,46
84,-115.56,32.78,29.0,1568.0,283.0,848.0,245.0,3.1597,76200.0,15
85,-115.56,32.76,15.0,1278.0,217.0,653.0,185.0,4.4821,140300.0,78
86,-115.57,32.85,33.0,1365.0,269.0,825.0,250.0,3.2396,62300.0,39
87,-115.57,32.85,17.0,1039.0,256.0,728.0,246.0,1.7411,63500.0,19
88,-115.57,32.84,29.0,1207.0,301.0,804.0,288.0,1.9531,61100.0,59
89,-115.57,32.83,31.0,1494.0,289.0,959.0,284.0,3.5282,67500.0,63
90,-115.57,32.80,16.0,2276.0,594.0,1184.0,513.0,1.8750,93800.0,44
91,-115.57,32.79,34.0,1152.0,208.0,621.0,208.0,3.6042,73600.0,23
92,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0,51
93,-115.57,32.78,15.0,1413.0,279.0,803.0,277.0,4.3021,87500.0,32
94,-115.58,33.88,21.0,1161.0,282.0,724.0,186.0,3.1827,71700.0,79
95,-115.58,32.81,5.0,805.0,143.0,458.0,143.0,4.4750,96300.0,72
96,-115.58,32.81,10.0,1088.0,203.0,533.0,201.0,3.6597,87500.0,88
97,-115.58,32.79,14.0,1687.0,507.0,762.0,451.0,1.6635,64400.0,26
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0,55
99,-115.59,32.85,20.0,1608.0,274.0,862.0,248.0,4.8750,90800.0,36

### webscraping
https://www.football-data.co.uk/data.php

In [ ]:
import pandas as pd
df=pd.read_csv(" https://www.football-data.co.uk/mmz4281/2324/E0.csv")

In [ ]:
df.rename(columns={'FTHG':"home_goals",'FTAG':"away_goals"},inplace=True)

In [ ]:
leagues=['E0','E2','E3']
frames=[]
root="https://www.football-data.co.uk/mmz4281/"
for league in leagues:
  for season in range(15,21):
    df=pd.read_csv(root+str(season)+str(season+1)+'/'+league+'.csv',encoding='utf-8')
    df.insert(1,'season',season)
    frames.append(df)
len(frames)
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
5,E0,15,08/08/2015,Norwich,Crystal Palace,1,3,A,0,1,...,1.67,27,0.00,1.83,1.78,2.17,2.08,2.46,3.39,3.14
6,E0,15,09/08/2015,Arsenal,West Ham,0,2,A,0,1,...,2.22,27,-1.50,1.96,1.89,2.06,1.96,1.24,6.75,15.00
7,E0,15,09/08/2015,Newcastle,Southampton,2,2,D,1,1,...,1.70,27,0.00,2.06,1.98,1.92,1.87,3.09,3.28,2.55
8,E0,15,09/08/2015,Stoke,Liverpool,0,1,A,0,0,...,1.75,26,0.25,2.00,1.95,1.96,1.91,3.89,3.51,2.09
9,E0,15,10/08/2015,West Brom,Man City,0,3,A,0,2,...,2.04,26,1.00,1.78,1.74,2.24,2.14,6.46,4.08,1.61
10,E0,15,14/08/2015,Aston Villa,Man United,0,1,A,0,1,...,1.71,26,0.75,2.01,1.95,1.96,1.91,5.06,3.76,1.80
11,E0,15,15/08/2015,Southampton,Everton,0,3,A,0,2,...,1.68,28,-0.50,1.98,1.92,1.99,1.93,2.03,3.54,4.08
12,E0,15,15/08/2015,Sunderland,Norwich,1,3,A,0,2,...,1.63,27,0.00,1.80,1.75,2.18,2.12,2.86,3.39,2.66
13,E0,15,15/08/2015,Swansea,Newcastle,2,0,H,1,0,...,1.86,28,-0.50,1.95,1.91,2.00,1.94,1.85,3.86,4.49
14,E0,15,15/08/2015,Tottenham,Stoke,2,2,D,2,0,...,1.87,27,-0.75,2.03,1.97,1.93,1.88,1.74,3.76,5.55
15,E0,15,15/08/2015,Watford,West Brom,0,0,D,0,0,...,1.71,27,-0.25,1.96,1.91,2.01,1.94,2.09,3.62,3.76
16,E0,15,15/08/2015,West Ham,Leicester,1,2,A,0,2,...,1.90,27,-0.25,1.98,1.92,1.99,1.93,2.38,3.54,3.15
17,E0,15,16/08/2015,Crystal Palace,Arsenal,1,2,A,1,1,...,1.96,27,0.75,2.01,1.95,1.95,1.91,5.40,4.08,1.69
18,E0,15,16/08/2015,Man City,Chelsea,3,0,H,1,0,...,1.82,28,-0.50,2.12,2.06,1.87,1.81,2.01,3.69,3.97
19,E0,15,17/08/2015,Liverpool,Bournemouth,1,0,H,1,0,...,2.05,25,-1.00,1.76,1.72,2.26,2.17,1.54,4.37,7.07
20,E0,15,22/08/2015,Crystal Palace,Aston Villa,2,1,H,0,0,...,1.73,27,-0.50,1.87,1.83,2.09,2.03,1.81,3.79,4.93
21,E0,15,22/08/2015,Leicester,Tottenham,1,1,D,0,0,...,1.97,27,0.00,1.96,1.90,2.01,1.93,2.61,3.50,2.85
22,E0,15,22/08/2015,Man United,Newcastle,0,0,D,0,0,...,2.06,26,-1.25,1.91,1.87,2.04,1.99,1.34,5.44,11.12
23,E0,15,22/08/2015,Norwich,Stoke,1,1,D,1,1,...,1.69,26,-0.25,2.02,1.97,1.94,1.89,2.15,3.42,3.82
24,E0,15,22/08/2015,Sunderland,Swansea,1,1,D,0,1,...,1.67,26,0.50,1.84,1.80,2.14,2.06,3.91,3.55,2.07
25,E0,15,22/08/2015,West Ham,Bournemouth,3,4,A,0,2,...,1.89,26,-0.25,2.08,2.01,1.89,1.84,2.64,3.51,2.81
26,E0,15,23/08/2015,Everton,Man City,0,2,A,0,0,...,2.20,26,0.75,1.96,1.92,1.99,1.93,5.47,4.10,1.68
27,E0,15,23/08/2015,Watford,Southampton,0,0,D,0,0,...,1.70,27,0.00,1.96,1.91,1.99,1.93,2.76,3.34,2.79
28,E0,15,23/08/2015,West Brom,Chelsea,2,3,A,1,3,...,1.74,26,0.75,2.11,2.04,1.87,1.82,7.25,4.12,1.56
29,E0,15,24/08/2015,Arsenal,Liverpool,0,0,D,0,0,...,2.02,24,-0.50,1.74,1.70,2.28,2.21,1.80,4.05,4.60
30,E0,15,29/08/2015,Aston Villa,Sunderland,2,2,D,2,1,...,1.64,26,-0.50,1.95,1.89,2.02,1.96,2.12,3.31,4.07
31,E0,15,29/08/2015,Bournemouth,Leicester,1,1,D,1,0,...,1.94,25,-0.25,1.88,1.84,2.08,2.02,2.06,3.65,3.82
32,E0,15,29/08/2015,Chelsea,Crystal Palace,1,2,A,0,0,...,2.15,25,-1.50,2.12,2.05,1.85,1.81,1.37,5.10,10.31
33,E0,15,29/08/2015,Liverpool,West Ham,0,3,A,0,2,...,2.17,26,-1.50,2.10,2.02,1.88,1.84,1.37,5.28,9.74
34,E0,15,29/08/2015,Man City,Watford,2,0,H,0,0,...,2.98,26,-2.00,1.95,1.90,2.00,1.95,1.22,7.05,16.50
35,E0,15,29/08/2015,Newcastle,Arsenal,0,1,A,0,0,...,2.00,24,1.00,1.86,1.81,2.12,2.06,5.81,4.48,1.60
36,E0,15,29/08/2015,Stoke,West Brom,0,1,A,0,1,...,1.64,26,-0.50,1.96,1.92,1.99,1.93,2.16,3.27,3.98
37,E0,15,29/08/2015,Tottenham,Everton,0,0,D,0,0,...,1.96,26,-0.50,1.97,1.92,1.98,1.93,2.10,3.55,3.81
38,E0,15,30/08/2015,Southampton,Norwich,3,0,H,1,0,...,1.79,26,-0.50,2.06,2.01,1.90,1.85,2.11,3.40,3.95
39,E0,15,30/08/2015,Swansea,Man United,2,1,H,0,0,...,1.74,25,0.25,2.03,1.98,1.93,1.88,3.82,3.41,2.15
40,E0,15,12/09/2015,Arsenal,Stoke,2,0,H,1,0,...,2.25,24,-1.50,1.87,1.80,2.12,2.05,1.30,6.30,11.00
41,E0,15,12/09/2015,Crystal Palace,Man City,0,1,A,0,0,...,2.27,25,1.00,1.82,1.78,2.16,2.09,4.95,3.89,1.78
42,E0,15,12/09/2015,Everton,Chelsea,3,1,H,2,1,...,1.82,25,0.50,1.93,1.88,2.03,1.97,3.56,3.51,2.20
43,E0,15,12/09/2015,Man United,Liverpool,3,1,H,0,0,...,1.70,24,-0.50,1.96,1.92,2.00,1.93,1.94,3.41,4.70
44,E0,15,12/09/2015,Norwich,Bournemouth,3,1,H,1,0,...,1.89,23,-0.25,2.04,1.99,1.91,1.87,2.42,3.48,3.13
45,E0,15,12/09/2015,Watford,Swansea,1,0,H,0,0,...,1.70,24,0.00,1.95,1.89,2.01,1.95,2.62,3.39,2.92
46,E0,15,12/09/2015,West Brom,Southampton,0,0,D,0,0,...,1.58,23,0.25,1.85,1.81,2.12,2.06,3.25,3.38,2.40
47,E0,15,13/09/2015,Leicester,Aston Villa,3,2,H,0,1,...,1.89,24,-0.50,1.89,1.85,2.08,2.01,1.88,3.78,4.47
48,E0,15,13/09/2015,Sunderland,Tottenham,0,1,A,0,0,...,1.85,24,0.50,2.01,1.95,1.94,1.90,4.26,3.69,1.94
49,E0,15,14/09/2015,West Ham,Newcastle,2,0,H,1,0,...,1.91,22,0.00,1.63,1.58,2.51,2.42,2.09,3.63,3.77
50,E0,15,19/09/2015,Aston Villa,West Brom,0,1,A,0,1,...,1.57,24,-0.25,1.98,1.93,1.98,1.93,2.40,3.18,3.46
51,E0,15,19/09/2015,Bournemouth,Sunderland,2,0,H,2,0,...,1.93,24,-0.75,1.95,1.90,2.01,1.96,1.57,4.75,5.75
52,E0,15,19/09/2015,Chelsea,Arsenal,2,0,H,0,0,...,2.02,24,-0.25,2.11,2.05,1.85,1.82,2.65,3.46,2.82
53,E0,15,19/09/2015,Man City,West Ham,1,2,A,1,2,...,2.71,25,-1.50,1.77,1.73,2.21,2.17,1.29,6.20,11.50
54,E0,15,19/09/2015,Newcastle,Watford,1,2,A,0,2,...,1.68,25,0.00,1.81,1.76,2.20,2.11,2.16,3.47,3.73
55,E0,15,19/09/2015,Stoke,Leicester,2,2,D,2,0,...,1.77,24,0.00,1.77,1.73,2.21,2.15,2.99,3.45,2.53
56,E0,15,19/09/2015,Swansea,Everton,0,0,D,0,0,...,1.78,24,-0.25,1.98,1.93,1.97,1.92,2.21,3.45,3.61
57,E0,15,20/09/2015,Liverpool,Norwich,1,1,D,0,0,...,1.93,25,-1.00,2.26,2.16,1.77,1.73,1.59,4.23,6.50
58,E0,15,20/09/2015,Southampton,Man United,2,3,A,1,1,...,1.62,24,0.00,2.26,2.17,1.76,1.72,3.45,3.28,2.35
59,E0,15,20/09/2015,Tottenham,Crystal Palace,1,0,H,0,0,...,1.89,25,-0.50,2.02,1.97,1.94,1.89,1.94,3.78,4.15
60,E0,15,26/09/2015,Leicester,Arsenal,2,5,A,1,2,...,2.18,26,0.50,2.13,2.07,1.85,1.80,4.76,4.03,1.78
61,E0,15,26/09/2015,Liverpool,Aston Villa,3,2,H,1,0,...,1.84,25,-1.00,1.93,1.89,2.02,1.98,1.50,4.42,7.79
62,E0,15,26/09/2015,Man United,Sunderland,3,0,H,1,0,...,2.38,25,-2.00,2.17,2.11,1.81,1.78,1.22,7.70,13.75
63,E0,15,26/09/2015,Newcastle,Chelsea,2,2,D,1,0,...,1.99,24,0.75,2.14,2.08,1.84,1.80,5.80,4.24,1.63
64,E0,15,26/09/2015,Southampton,Swansea,3,1,H,1,0,...,1.68,26,-0.50,2.05,2.00,1.92,1.86,1.85,3.71,4.79
65,E0,15,26/09/2015,Stoke,Bournemouth,2,1,H,1,0,...,1.78,25,0.00,1.81,1.76,2.20,2.11,2.43,3.49,3.10
66,E0,15,26/09/2015,Tottenham,Man City,4,1,H,1,1,...,2.11,26,0.50,1.98,1.94,1.96,1.92,3.49,3.51,2.23
67,E0,15,26/09/2015,West Ham,Norwich,2,2,D,1,1,...,1.89,25,-0.50,2.26,2.19,1.75,1.72,2.25,3.49,3.45
68,E0,15,27/09/2015,Watford,Crystal Palace,0,1,A,0,0,...,1.71,25,0.00,1.78,1.75,2.21,2.13,2.61,3.38,2.93
69,E0,15,28/09/2015,West Brom,Everton,2,3,A,1,0,...,1.64,23,0.00,2.17,2.10,1.82,1.77,3.02,3.36,2.55
70,E0,15,03/10/2015,Aston Villa,Stoke,0,1,A,0,0,...,1.67,24,-0.25,2.16,2.10,1.82,1.78,2.71,3.25,2.91
71,E0,15,03/10/2015,Bournemouth,Watford,1,1,D,1,1,...,1.80,27,-0.50,2.13,2.08,1.85,1.79,2.21,3.34,3.72
72,E0,15,03/10/2015,Chelsea,Southampton,1,3,A,1,1,...,1.91,25,-0.75,2.12,2.05,1.90,1.82,1.79,3.90,4.89
73,E0,15,03/10/2015,Crystal Palace,West Brom,2,0,H,0,0,...,1.70,25,-0.75,2.11,2.05,1.87,1.82,1.83,3.64,5.00
74,E0,15,03/10/2015,Man City,Newcastle,6,1,H,1,1,...,2.85,27,-2.00,2.12,2.02,1.90,1.84,1.22,7.30,14.85
75,E0,15,03/10/2015,Norwich,Leicester,1,2,A,0,1,...,2.08,26,-0.50,2.30,2.23,1.74,1.70,2.33,3.44,3.34
76,E0,15,03/10/2015,Sunderland,West Ham,2,2,D,2,1,...,1.86,24,0.25,1.86,1.83,2.10,2.03,3.03,3.55,2.45
77,E0,15,04/10/2015,Arsenal,Man United,3,0,H,3,0,...,1.97,25,-0.50,2.06,2.00,1.91,1.86,2.01,3.81,3.84
78,E0,15,04/10/2015,Everton,Liverpool,1,1,D,1,1,...,1.82,25,0.00,1.97,1.89,2.01,1.96,3.16,3.44,2.42
79,E0,15,04/10/2015,Swansea,Tottenham,2,2,D,2,1,...,1.81,26,0.00,1.95,1.90,2.01,1.94,2.68,3.46,2.79
80,E0,15,17/10/2015,Chelsea,Aston Villa,2,0,H,1,0,...,2.24,28,-1.50,2.06,1.99,1.90,1.87,1.33,5.83,10.20
81,E0,15,17/10/2015,Crystal Palace,West Ham,1,3,A,1,1,...,1.90,27,-0.50,2.02,1.96,1.93,1.89,1.96,3.77,4.08
82,E0,15,17/10/2015,Everton,Man United,0,3,A,0,2,...,1.78,25,0.25,1.88,1.85,2.07,2.01,3.29,3.48,2.33
83,E0,15,17/10/2015,Man City,Bournemouth,5,1,H,4,1,...,2.46,28,-1.50,2.02,1.96,1.94,1.89,1.34,5.38,10.93
84,E0,15,17/10/2015,Southampton,Leicester,2,2,D,2,0,...,2.06,26,-0.50,1.79,1.74,2.21,2.14,1.73,3.94,5.32
85,E0,15,17/10/2015,Tottenham,Liverpool,0,0,D,0,0,...,2.01,25,0.00,1.80,1.75,2.20,2.13,2.28,3.52,3.36
86,E0,15,17/10/2015,Watford,Arsenal,0,3,A,0,0,...,2.10,28,1.00,1.91,1.86,2.06,2.00,6.75,4.54,1.53
87,E0,15,17/10/2015,West Brom,Sunderland,1,0,H,0,0,...,1.62,27,-0.50,2.09,2.03,1.86,1.83,2.15,3.35,3.91
88,E0,15,18/10/2015,Newcastle,Norwich,6,2,H,3,2,...,1.91,27,0.00,1.87,1.83,2.09,2.01,2.48,3.54,2.99
89,E0,15,19/10/2015,Swansea,Stoke,0,1,A,0,1,...,1.67,25,-0.50,2.08,2.01,1.89,1.85,1.88,3.66,4.62
90,E0,15,24/10/2015,Arsenal,Everton,2,1,H,2,1,...,2.47,23,-1.50,2.17,2.12,1.80,1.76,1.39,5.30,8.80
91,E0,15,24/10/2015,Aston Villa,Swansea,1,2,A,0,0,...,1.59,24,0.00,2.15,2.06,1.85,1.80,3.01,3.25,2.63
92,E0,15,24/10/2015,Leicester,Crystal Palace,1,0,H,0,0,...,2.08,23,-0.25,1.92,1.89,2.04,1.98,2.17,3.57,3.58
93,E0,15,24/10/2015,Norwich,West Brom,0,1,A,0,0,...,1.71,24,-0.50,2.02,1.97,1.94,1.89,1.98,3.74,4.03
94,E0,15,24/10/2015,Stoke,Watford,0,2,A,0,1,...,1.61,23,-0.50,2.11,2.06,1.85,1.81,2.10,3.49,3.89
95,E0,15,24/10/2015,West Ham,Chelsea,2,1,H,1,0,...,2.10,24,0.50,1.94,1.90,2.01,1.96,4.21,3.86,1.91
96,E0,15,25/10/2015,Bournemouth,Tottenham,1,5,A,1,3,...,1.83,22,0.25,2.02,1.97,1.93,1.90,3.52,3.55,2.20
97,E0,15,25/10/2015,Liverpool,Southampton,1,1,D,0,0,...,1.84,24,-0.50,2.08,2.04,1.86,1.83,2.09,3.53,3.87
98,E0,15,25/10/2015,Man United,Man City,0,0,D,0,0,...,1.97,24,0.00,1.89,1.85,2.09,2.00,2.63,3.32,2.95
99,E0,15,25/10/2015,Sunderland,Newcastle,3,0,H,1,0,...,1.85,24,0.00,1.87,1.81,2.11,2.05,2.63,3.38,2.91
100,E0,15,31/10/2015,Chelsea,Liverpool,1,3,A,1,1,...,1.77,28,-0.50,2.13,2.06,1.86,1.81,2.12,3.47,3.84
101,E0,15,31/10/2015,Crystal Palace,Man United,0,0,D,0,0,...,1.70,28,0.50,1.88,1.82,2.10,2.04,4.46,3.56,1.94
102,E0,15,31/10/2015,Man City,Norwich,2,1,H,0,0,...,2.68,28,-1.50,1.89,1.83,2.10,2.03,1.27,6.59,12.50
103,E0,15,31/10/2015,Newcastle,Stoke,0,0,D,0,0,...,1.77,27,-0.25,2.06,2.00,1.91,1.86,2.37,3.39,3.29
104,E0,15,31/10/2015,Swansea,Arsenal,0,3,A,0,0,...,2.05,26,0.75,1.99,1.92,2.00,1.94,4.73,4.01,1.79
105,E0,15,31/10/2015,Watford,West Ham,2,0,H,1,0,...,1.79,28,0.00,1.84,1.80,2.14,2.06,2.50,3.42,3.05
106,E0,15,31/10/2015,West Brom,Leicester,2,3,A,1,0,...,1.77,28,0.00,2.08,2.00,1.92,1.84,2.97,3.38,2.58
107,E0,15,01/11/2015,Everton,Sunderland,6,2,H,2,1,...,2.09,29,-1.00,1.84,1.78,2.16,2.09,1.48,4.70,7.50
108,E0,15,01/11/2015,Southampton,Bournemouth,2,0,H,2,0,...,2.05,28,-1.00,1.95,1.90,1.99,1.95,1.53,4.41,7.22
109,E0,15,02/11/2015,Tottenham,Aston Villa,3,1,H,2,0,...,2.02,25,-1.00,1.71,1.67,2.36,2.26,1.40,5.09,9.32
110,E0,15,07/11/2015,Bournemouth,Newcastle,0,1,A,0,1,...,1.98,23,-0.25,1.91,1.88,2.06,1.99,2.22,3.62,3.40
111,E0,15,07/11/2015,Leicester,Watford,2,1,H,0,0,...,2.00,24,-0.50,1.88,1.83,2.09,2.03,1.93,3.71,4.34
112,E0,15,07/11/2015,Man United,West Brom,2,0,H,0,0,...,1.87,25,-1.50,2.08,2.01,1.88,1.85,1.36,5.10,11.15
113,E0,15,07/11/2015,Norwich,Swansea,1,0,H,0,0,...,1.84,23,0.00,1.79,1.76,2.20,2.11,2.54,3.43,2.99
114,E0,15,07/11/2015,Stoke,Chelsea,1,0,H,0,0,...,1.74,24,0.50,1.88,1.83,2.09,2.04,4.53,3.66,1.90
115,E0,15,07/11/2015,Sunderland,Southampton,0,1,A,0,0,...,1.84,23,0.75,1.88,1.84,2.12,2.03,4.70,4.00,1.79
116,E0,15,07/11/2015,West Ham,Everton,1,1,D,1,1,...,2.07,24,0.00,1.87,1.83,2.09,2.02,2.45,3.59,2.99
117,E0,15,08/11/2015,Arsenal,Tottenham,1,1,D,0,1,...,2.33,22,-0.75,1.89,1.85,2.08,2.02,1.80,3.96,4.72
118,E0,15,08/11/2015,Aston Villa,Man City,0,0,D,0,0,...,2.15,23,1.25,1.94,1.88,2.02,1.97,8.55,5.05,1.42
119,E0,15,08/11/2015,Liverpool,Crystal Palace,1,2,A,1,1,...,1.87,22,-0.75,1.91,1.86,2.06,2.00,1.64,3.92,6.51
120,E0,15,21/11/2015,Chelsea,Norwich,1,0,H,0,0,...,2.12,26,-1.50,2.29,2.23,1.75,1.69,1.41,5.03,8.82
121,E0,15,21/11/2015,Everton,Aston Villa,4,0,H,3,0,...,1.89,26,-1.00,2.07,1.99,1.92,1.88,1.72,4.01,5.31
122,E0,15,21/11/2015,Man City,Liverpool,1,4,A,1,3,...,2.09,25,-0.75,1.86,1.82,2.09,2.05,1.89,3.72,4.48
123,E0,15,21/11/2015,Newcastle,Leicester,0,3,A,0,1,...,2.17,24,0.00,2.07,2.01,1.88,1.84,2.94,3.57,2.50
124,E0,15,21/11/2015,Southampton,Stoke,0,1,A,0,1,...,1.78,26,-1.00,2.12,2.04,1.87,1.83,1.68,3.87,5.98
125,E0,15,21/11/2015,Swansea,Bournemouth,2,2,D,2,2,...,1.82,24,-0.50,1.92,1.88,2.04,1.98,2.24,3.37,3.61
126,E0,15,21/11/2015,Watford,Man United,1,2,A,0,1,...,1.59,24,0.75,1.67,1.63,2.44,2.34,4.02,3.38,2.10
127,E0,15,21/11/2015,West Brom,Arsenal,2,1,H,2,1,...,2.02,26,1.00,2.05,1.96,1.97,1.91,6.11,4.28,1.60
128,E0,15,22/11/2015,Tottenham,West Ham,4,1,H,2,0,...,2.14,26,-1.00,1.99,1.91,2.00,1.96,1.58,4.32,6.44
129,E0,15,23/11/2015,Crystal Palace,Sunderland,0,1,A,0,0,...,1.93,24,-1.00,2.03,1.93,1.98,1.93,1.55,4.52,6.60
130,E0,15,28/11/2015,Aston Villa,Watford,2,3,A,1,1,...,1.58,28,-0.25,2.35,2.29,1.69,1.66,2.76,3.27,2.84
131,E0,15,28/11/2015,Bournemouth,Everton,3,3,D,0,2,...,2.03,28,0.00,2.16,2.09,1.82,1.78,2.65,3.66,2.70
132,E0,15,28/11/2015,Crystal Palace,Newcastle,5,1,H,3,1,...,2.02,29,-0.75,1.90,1.87,2.05,1.99,1.71,4.10,5.17
133,E0,15,28/11/2015,Leicester,Man United,1,1,D,1,1,...,1.78,27,0.25,1.92,1.88,2.03,1.99,3.26,3.49,2.34
134,E0,15,28/11/2015,Man City,Southampton,3,1,H,2,0,...,2.23,31,-1.00,1.98,1.93,2.00,1.92,1.57,4.40,6.37
135,E0,15,28/11/2015,Sunderland,Stoke,2,0,H,0,0,...,1.63,29,0.25,1.85,1.80,2.13,2.07,3.05,3.26,2.59
136,E0,15,29/11/2015,Liverpool,Swansea,1,0,H,0,0,...,2.01,29,-1.00,1.81,1.75,2.23,2.14,1.48,4.55,7.95
137,E0,15,29/11/2015,Norwich,Arsenal,1,1,D,1,1,...,2.25,31,1.00,1.88,1.85,2.09,2.01,6.50,4.41,1.56
138,E0,15,29/11/2015,Tottenham,Chelsea,0,0,D,0,0,...,1.92,27,-0.25,2.23,2.17,1.78,1.73,2.66,3.39,2.86
139,E0,15,29/11/2015,West Ham,West Brom,1,1,D,1,0,...,1.69,29,-0.50,2.10,2.04,1.87,1.83,2.13,3.35,3.96
140,E0,15,05/12/2015,Arsenal,Sunderland,3,1,H,1,1,...,2.30,28,-1.50,1.85,1.79,2.14,2.08,1.29,6.53,11.18
141,E0,15,05/12/2015,Chelsea,Bournemouth,0,1,A,0,0,...,2.24,27,-1.25,1.90,1.83,2.09,2.03,1.43,4.79,9.04
142,E0,15,05/12/2015,Man United,West Ham,0,0,D,0,0,...,1.83,28,-1.00,1.75,1.70,2.26,2.20,1.46,4.68,8.18
143,E0,15,05/12/2015,Southampton,Aston Villa,1,1,D,0,1,...,1.87,29,-1.00,1.88,1.83,2.09,2.03,1.50,4.55,7.40
144,E0,15,05/12/2015,Stoke,Man City,2,0,H,2,0,...,2.01,27,0.75,2.01,1.97,1.94,1.89,5.21,3.94,1.74
145,E0,15,05/12/2015,Swansea,Leicester,0,3,A,0,2,...,1.98,28,0.00,1.98,1.91,2.01,1.94,2.55,3.33,3.06
146,E0,15,05/12/2015,Watford,Norwich,2,0,H,1,0,...,1.80,27,-0.25,1.88,1.84,2.08,2.02,2.35,3.43,3.30
147,E0,15,05/12/2015,West Brom,Tottenham,1,1,D,1,1,...,1.69,27,0.50,2.09,2.02,1.87,1.84,4.80,3.86,1.81
148,E0,15,06/12/2015,Newcastle,Liverpool,2,0,H,0,0,...,2.08,29,1.00,1.88,1.85,2.08,2.01,6.40,4.48,1.56
149,E0,15,07/12/2015,Everton,Crystal Palace,1,1,D,0,0,...,2.02,25,-0.25,1.79,1.75,2.18,2.12,2.14,3.43,3.83
150,E0,15,12/12/2015,Bournemouth,Man United,2,1,H,1,1,...,1.69,27,0.25,1.99,1.94,1.97,1.92,3.30,3.27,2.43
151,E0,15,12/12/2015,Crystal Palace,Southampton,1,0,H,1,0,...,1.72,27,0.00,1.83,1.79,2.15,2.07,2.45,3.41,3.14
152,E0,15,12/12/2015,Man City,Swansea,2,1,H,1,0,...,2.46,30,-1.50,1.90,1.84,2.08,2.02,1.35,5.60,9.65
153,E0,15,12/12/2015,Norwich,Everton,1,1,D,0,1,...,1.96,27,0.00,2.12,2.07,1.83,1.79,3.16,3.48,2.40
154,E0,15,12/12/2015,Sunderland,Watford,0,1,A,0,1,...,1.69,27,0.00,2.02,1.98,1.92,1.87,2.81,3.31,2.76
155,E0,15,12/12/2015,West Ham,Stoke,0,0,D,0,0,...,1.67,27,0.00,1.86,1.82,2.09,2.04,2.59,3.25,3.07
156,E0,15,13/12/2015,Aston Villa,Arsenal,0,2,A,0,2,...,1.93,30,1.00,1.94,1.89,2.03,1.96,6.50,4.39,1.56
157,E0,15,13/12/2015,Liverpool,West Brom,2,2,D,1,1,...,1.78,28,-1.50,2.38,2.27,1.70,1.67,1.44,4.70,8.95
158,E0,15,13/12/2015,Tottenham,Newcastle,1,2,A,1,0,...,2.35,30,-1.50,2.10,2.03,1.88,1.83,1.37,5.54,9.01
159,E0,15,14/12/2015,Leicester,Chelsea,2,1,H,1,0,...,1.89,26,0.25,1.88,1.84,2.07,2.02,3.52,3.52,2.21
160,E0,15,19/12/2015,Chelsea,Sunderland,3,1,H,2,0,...,2.05,31,-1.50,1.97,1.90,2.01,1.95,1.32,5.99,10.80
161,E0,15,19/12/2015,Everton,Leicester,2,3,A,1,1,...,2.27,29,-0.50,2.08,2.03,1.89,1.83,2.05,3.78,3.73
162,E0,15,19/12/2015,Man United,Norwich,1,2,A,0,1,...,1.89,29,-1.00,1.80,1.75,2.20,2.13,1.43,4.85,8.75
163,E0,15,19/12/2015,Newcastle,Aston Villa,1,1,D,1,0,...,1.79,28,-0.50,2.04,1.99,1.93,1.88,2.01,3.55,4.15
164,E0,15,19/12/2015,Southampton,Tottenham,0,2,A,0,2,...,1.80,27,0.00,1.91,1.87,2.04,1.99,2.72,3.33,2.85
165,E0,15,19/12/2015,Stoke,Crystal Palace,1,2,A,0,1,...,1.63,29,-0.25,2.14,2.07,1.84,1.80,2.46,3.30,3.21
166,E0,15,19/12/2015,West Brom,Bournemouth,1,2,A,0,0,...,1.69,28,-0.25,2.25,2.17,2.52,1.76,2.86,3.33,2.70
167,E0,15,20/12/2015,Swansea,West Ham,0,0,D,0,0,...,1.70,28,-0.50,2.10,2.05,1.86,1.82,2.07,3.44,4.08
168,E0,15,20/12/2015,Watford,Liverpool,3,0,H,2,0,...,1.74,28,0.50,1.96,1.91,2.01,1.94,3.68,3.58,2.13
169,E0,15,21/12/2015,Arsenal,Man City,2,1,H,2,0,...,2.15,27,-0.25,2.08,2.02,1.88,1.84,2.49,3.49,3.01
170,E0,15,26/12/2015,Aston Villa,West Ham,1,1,D,0,1,...,1.62,28,0.00,1.90,1.86,2.07,1.99,2.53,3.23,3.17
171,E0,15,26/12/2015,Bournemouth,Crystal Palace,0,0,D,0,0,...,1.84,29,-0.25,2.13,2.05,1.86,1.82,2.14,3.48,3.77
172,E0,15,26/12/2015,Chelsea,Watford,2,2,D,1,1,...,2.04,29,-1.00,1.88,1.84,2.10,2.02,1.50,4.52,7.55
173,E0,15,26/12/2015,Liverpool,Leicester,1,0,H,0,0,...,2.21,29,-0.50,1.96,1.92,1.98,1.94,1.99,3.79,3.94
174,E0,15,26/12/2015,Man City,Sunderland,4,1,H,3,0,...,2.86,31,-2.00,1.96,1.92,1.99,1.93,1.21,7.95,14.78
175,E0,15,26/12/2015,Newcastle,Everton,0,1,A,0,0,...,2.07,29,0.25,2.03,1.96,1.94,1.89,3.62,3.61,2.14
176,E0,15,26/12/2015,Southampton,Arsenal,4,0,H,1,0,...,1.86,29,0.25,2.10,2.04,1.88,1.83,3.64,3.43,2.20
177,E0,15,26/12/2015,Stoke,Man United,2,0,H,2,0,...,1.57,29,0.25,1.89,1.86,2.07,2.01,3.79,3.25,2.23
178,E0,15,26/12/2015,Swansea,West Brom,1,0,H,1,0,...,1.54,29,-0.50,2.00,1.95,1.98,1.91,1.92,3.42,4.86
179,E0,15,26/12/2015,Tottenham,Norwich,3,0,H,2,0,...,2.15,30,-1.00,1.74,1.69,2.30,2.23,1.47,4.54,8.40
180,E0,15,28/12/2015,Arsenal,Bournemouth,2,0,H,1,0,...,2.26,30,-1.50,2.32,2.22,1.75,1.70,1.54,4.35,7.15
181,E0,15,28/12/2015,Crystal Palace,Swansea,0,0,D,0,0,...,1.64,30,-0.25,1.83,1.79,2.17,2.09,2.04,3.34,4.35
182,E0,15,28/12/2015,Everton,Stoke,3,4,A,1,2,...,1.79,30,-0.50,1.95,1.91,2.01,1.95,1.83,3.72,4.85
183,E0,15,28/12/2015,Man United,Chelsea,0,0,D,0,0,...,1.66,28,0.00,1.85,1.81,2.12,2.05,2.48,3.26,3.22
184,E0,15,28/12/2015,Norwich,Aston Villa,2,0,H,1,0,...,1.72,30,-0.50,2.09,2.03,1.89,1.84,1.93,3.70,4.36
185,E0,15,28/12/2015,Watford,Tottenham,1,2,A,1,1,...,1.77,30,0.50,1.88,1.82,2.09,2.05,3.28,3.32,2.42
186,E0,15,28/12/2015,West Brom,Newcastle,1,0,H,0,0,...,1.66,30,-0.25,1.90,1.85,2.07,2.02,2.16,3.34,3.87
187,E0,15,28/12/2015,West Ham,Southampton,2,1,H,0,1,...,1.67,29,0.25,2.01,1.96,1.95,1.90,3.64,3.41,2.21
188,E0,15,29/12/2015,Leicester,Man City,0,0,D,0,0,...,2.38,29,0.50,2.11,2.05,1.85,1.81,4.17,3.88,1.91
189,E0,15,30/12/2015,Sunderland,Liverpool,0,1,A,0,0,...,1.81,28,0.50,2.32,2.25,1.74,1.68,5.77,4.09,1.66
190,E0,15,02/01/2016,Arsenal,Newcastle,1,0,H,0,0,...,2.56,30,-1.50,1.81,1.76,2.18,2.11,1.24,7.25,12.75
191,E0,15,02/01/2016,Leicester,Bournemouth,0,0,D,0,0,...,2.03,29,-0.50,1.94,1.91,2.00,1.96,1.94,3.70,4.25
192,E0,15,02/01/2016,Man United,Swansea,2,1,H,0,0,...,1.66,30,-1.00,1.98,1.93,2.00,1.92,1.49,4.30,8.55

### Filter DataFrame

In [ ]:
df=frames[0]
df.columns

Index(['Div', 'season', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF',
       'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH',
       'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD',
       'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH',
       'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5',
       'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH',
       'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

In [ ]:
df['HomeTeam']=="Man City"

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18      True
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34      True
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53      True
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83      True
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102     True
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122     True
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134     True
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152     True
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174     True
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205     True
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213     True
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242     True
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259     True
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280     True
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299     True
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315     True
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342     True
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364     True
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
Name: HomeTeam, dtype: bool

In [ ]:
df[df['HomeTeam']=="Man City"].value_counts("HomeTeam")

HomeTeam
Man City    19
Name: count, dtype: int64

In [ ]:
import numpy as np
np.where(df['BbAH']>26,'True','False')

array(['False', 'True', 'False', 'False', 'False', 'True', 'True', 'True',
       'False', 'False', 'False', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'False', 'True', 'True', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'True', 'True', 'False', 'True', 'False', 'False', 'True', 'True',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'True',
       'True', 'True', 'False', 'True', 'True', 'True', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'False', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'False', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'False', 'True', 'False', 'True', 'True', 'False', 'False', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True',
       'True'], dtype='<U5')

In [ ]:
#Creating a conditional column
conditions=[
    df['AC']<5,
    df['AC']>5,
]
values=['Less than 5',"More than 5"]
np.select(conditions,values)

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [ ]:
#isin() SingleFiltering
df[df['AC'].isin([1,2,3,4,5])].value_counts('AC')

AC
4    66
3    58
5    55
2    37
1    19
Name: count, dtype: int64

In [ ]:
#duplicated
~df.duplicated('AC')

0       True
1       True
2       True
3      False
4      False
5       True
6      False
7       True
8       True
9      False
10     False
11      True
12     False
13     False
14     False
15     False
16     False
17     False
18      True
19     False
20     False
21      True
22     False
23      True
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42      True
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78      True
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99      True
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177     True
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188     True
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
dtype: bool

In [ ]:
df.drop_duplicates('HomeTeam',keep='last',)

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
356,E0,15,07/05/2016,Aston Villa,Newcastle,0,0,D,0,0,...,1.94,30,0.75,2.09,2.03,1.89,1.84,5.05,4.13,1.72
357,E0,15,07/05/2016,Bournemouth,West Brom,1,1,D,0,1,...,1.88,29,-0.50,1.96,1.91,2.00,1.95,1.93,3.65,4.38
358,E0,15,07/05/2016,Crystal Palace,Stoke,2,1,H,0,1,...,1.75,29,-0.50,2.07,2.03,1.88,1.84,2.02,3.54,4.12
359,E0,15,07/05/2016,Leicester,Everton,3,1,H,2,0,...,2.26,29,-0.50,1.91,1.86,2.05,2.00,1.83,4.21,4.21
364,E0,15,08/05/2016,Man City,Arsenal,2,2,D,1,1,...,2.14,28,0.00,1.86,1.81,2.11,2.05,2.22,3.61,3.41
365,E0,15,08/05/2016,Tottenham,Southampton,1,2,A,1,1,...,2.04,29,-0.50,2.03,1.99,1.92,1.87,2.25,3.44,3.49
366,E0,15,10/05/2016,West Ham,Man United,3,2,H,1,0,...,1.95,29,0.25,1.85,1.80,2.12,2.07,3.15,3.47,2.41
367,E0,15,11/05/2016,Liverpool,Chelsea,1,1,D,0,1,...,2.24,28,-0.50,2.01,1.97,1.94,1.89,1.71,4.36,4.81
368,E0,15,11/05/2016,Norwich,Watford,4,2,H,3,1,...,1.90,28,-0.75,2.13,2.07,1.83,1.79,1.88,3.98,4.19
369,E0,15,11/05/2016,Sunderland,Everton,3,0,H,2,0,...,2.11,29,-0.75,2.00,1.94,1.96,1.92,1.86,3.98,4.31
370,E0,15,15/05/2016,Arsenal,Aston Villa,4,0,H,1,0,...,3.08,30,-2.25,1.96,1.91,1.99,1.94,1.12,12.03,23.60
371,E0,15,15/05/2016,Chelsea,Leicester,1,1,D,0,0,...,2.25,30,-0.25,2.03,1.99,1.92,1.87,2.01,3.99,3.68
372,E0,15,15/05/2016,Everton,Norwich,3,0,H,2,0,...,2.34,30,-0.75,1.95,1.92,2.00,1.93,1.74,4.38,4.60
373,E0,15,15/05/2016,Newcastle,Tottenham,5,1,H,2,0,...,2.21,30,0.75,1.94,1.89,2.01,1.97,5.30,4.18,1.69
374,E0,15,15/05/2016,Southampton,Crystal Palace,4,1,H,1,0,...,2.26,31,-1.50,2.00,1.93,1.98,1.92,1.29,6.80,10.00
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [ ]:
df['HomeTeam'].unique()
df['HomeTeam'].nunique()

20

### Selecting data

### Understanding `.loc` and `.iloc` in Pandas

`.loc` and `.iloc` are two of the most commonly used indexers in pandas for selecting data from DataFrames and Series. While both are used for data selection, they differ significantly in how they interpret their arguments:

*   **`.loc` is primarily label-based indexing.** This means you use the actual labels (names) of the rows and columns to select data.
*   **`.iloc` is primarily integer-location based indexing.** This means you use the integer positions of the rows and columns to select data, similar to standard Python list or NumPy array indexing.

Let's break down each one with examples:

---

#### **1. `.loc` (Label-based indexing)**

`.loc` is used to select data by row and column labels. It can take one or two arguments:

*   `df.loc[row_label]`
*   `df.loc[row_label, column_label]`

**Key Characteristics:**
*   **Inclusive Slicing:** When slicing with labels (e.g., `start_label:end_label`), both the `start_label` and `end_label` are included in the selection.
*   **Labels Must Exist:** The labels you use for selection must be present in the DataFrame's index or columns, otherwise, it will raise a `KeyError`.
*   **Can take a boolean array:** You can pass a boolean Series or array to select rows based on a condition.

**Examples:**

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {'col1': [10, 20, 30, 40, 50],
        'col2': [100, 200, 300, 400, 500],
        'col3': ['A', 'B', 'C', 'D', 'E']}
index_labels = ['row1', 'row2', 'row3', 'row4', 'row5']
df_sample = pd.DataFrame(data, index=index_labels)
display("Original DataFrame:", df_sample)

# Select a single row by label
display("\nSelect row 'row3':", df_sample.loc['row3'])

# Select multiple rows by label list
display("\nSelect rows 'row1' and 'row4':", df_sample.loc[['row1', 'row4']])

# Select rows by label slicing (inclusive)
display("\nSelect rows from 'row2' to 'row4':", df_sample.loc['row2':'row4'])

# Select a single column by label
display("\nSelect column 'col2':", df_sample.loc[:, 'col2'])

# Select multiple columns by label list
display("\nSelect columns 'col1' and 'col3':", df_sample.loc[:, ['col1', 'col3']])

# Select columns by label slicing (inclusive)
display("\nSelect columns from 'col1' to 'col3':", df_sample.loc[:, 'col1':'col3'])

# Select a specific cell by row and column label
display("\nSelect cell at 'row2', 'col1':", df_sample.loc['row2', 'col1'])

# Select rows based on a condition
display("\nSelect rows where 'col1' > 20:", df_sample.loc[df_sample['col1'] > 20])

# Select rows based on a condition and specific columns
display("\nSelect 'col1' and 'col3' where 'col1' > 20:", df_sample.loc[df_sample['col1'] > 20, ['col1', 'col3']])

'Original DataFrame:'

      col1  col2 col3
row1    10   100    A
row2    20   200    B
row3    30   300    C
row4    40   400    D
row5    50   500    E

"\nSelect row 'row3':"

col1     30
col2    300
col3      C
Name: row3, dtype: object

"\nSelect rows 'row1' and 'row4':"

      col1  col2 col3
row1    10   100    A
row4    40   400    D

"\nSelect rows from 'row2' to 'row4':"

      col1  col2 col3
row2    20   200    B
row3    30   300    C
row4    40   400    D

"\nSelect column 'col2':"

row1    100
row2    200
row3    300
row4    400
row5    500
Name: col2, dtype: int64

"\nSelect columns 'col1' and 'col3':"

      col1 col3
row1    10    A
row2    20    B
row3    30    C
row4    40    D
row5    50    E

"\nSelect columns from 'col1' to 'col3':"

      col1  col2 col3
row1    10   100    A
row2    20   200    B
row3    30   300    C
row4    40   400    D
row5    50   500    E

"\nSelect cell at 'row2', 'col1':"

np.int64(20)

"\nSelect rows where 'col1' > 20:"

      col1  col2 col3
row3    30   300    C
row4    40   400    D
row5    50   500    E

"\nSelect 'col1' and 'col3' where 'col1' > 20:"

      col1 col3
row3    30    C
row4    40    D
row5    50    E


---

#### **2. `.iloc` (Integer-location based indexing)**

`.iloc` is used to select data by its integer position. It can take one or two arguments:

*   `df.iloc[row_position]`
*   `df.iloc[row_position, column_position]`

**Key Characteristics:**
*   **Exclusive Slicing:** When slicing with integer positions (e.g., `start_pos:end_pos`), the `end_pos` is **excluded**, similar to Python's built-in list slicing.
*   **Integer Positions Only:** Only integers are accepted for selection, not labels.
*   **Can take a boolean array:** You can pass a boolean Series or array to select rows based on a condition.

**Examples:**

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame (same as before for comparison)
data = {'col1': [10, 20, 30, 40, 50],
        'col2': [100, 200, 300, 400, 500],
        'col3': ['A', 'B', 'C', 'D', 'E']}
index_labels = ['row1', 'row2', 'row3', 'row4', 'row5']
df_sample = pd.DataFrame(data, index=index_labels)
display("Original DataFrame:", df_sample)

# Select a single row by integer position (0-indexed)
display("\nSelect row at position 2 (which is 'row3'):", df_sample.iloc[2])

# Select multiple rows by integer position list
display("\nSelect rows at positions 0 and 3 ('row1' and 'row4'):", df_sample.iloc[[0, 3]])

# Select rows by integer slicing (exclusive of end position)
display("\nSelect rows from position 1 to 3 (exclusive of 3, so 'row2' and 'row3'):", df_sample.iloc[1:3])

# Select a single column by integer position
display("\nSelect column at position 1 (which is 'col2'):", df_sample.iloc[:, 1])

# Select multiple columns by integer position list
display("\nSelect columns at positions 0 and 2 ('col1' and 'col3'):", df_sample.iloc[:, [0, 2]])

# Select columns by integer slicing (exclusive of end position)
display("\nSelect columns from position 0 to 2 (exclusive of 2, so 'col1' and 'col2'):", df_sample.iloc[:, 0:2])

# Select a specific cell by row and column integer position
display("\nSelect cell at row position 1, column position 0 ('row2', 'col1'):", df_sample.iloc[1, 0])

# Select rows based on a boolean condition (can be used with iloc for row selection)
display("\nSelect rows where 'col1' > 20 using iloc (row selection):", df_sample.iloc[df_sample['col1'] > 20])

'Original DataFrame:'

      col1  col2 col3
row1    10   100    A
row2    20   200    B
row3    30   300    C
row4    40   400    D
row5    50   500    E

"\nSelect row at position 2 (which is 'row3'):"

col1     30
col2    300
col3      C
Name: row3, dtype: object

"\nSelect rows at positions 0 and 3 ('row1' and 'row4'):"

      col1  col2 col3
row1    10   100    A
row4    40   400    D

"\nSelect rows from position 1 to 3 (exclusive of 3, so 'row2' and 'row3'):"

      col1  col2 col3
row2    20   200    B
row3    30   300    C

"\nSelect column at position 1 (which is 'col2'):"

row1    100
row2    200
row3    300
row4    400
row5    500
Name: col2, dtype: int64

"\nSelect columns at positions 0 and 2 ('col1' and 'col3'):"

      col1 col3
row1    10    A
row2    20    B
row3    30    C
row4    40    D
row5    50    E

"\nSelect columns from position 0 to 2 (exclusive of 2, so 'col1' and 'col2'):"

      col1  col2
row1    10   100
row2    20   200
row3    30   300
row4    40   400
row5    50   500

"\nSelect cell at row position 1, column position 0 ('row2', 'col1'):"

np.int64(20)

ValueError: iLocation based boolean indexing cannot use an indexable as a mask


---

#### **When to use `.loc` vs. `.iloc`?**

*   **Use `.loc`** when you know the exact labels of the rows and/or columns you want to select. It's more robust to changes in the DataFrame's structure (e.g., if a column's position changes but its name stays the same).
*   **Use `.iloc`** when you know the integer positions of the rows and/or columns you want to select. This is useful when iterating or when the exact position is more relevant than the label (e.g., selecting the first 5 rows).

It's a common practice to use `.loc` for clarity and maintainability, especially when your DataFrame's index or column names have semantic meaning.

In [ ]:
data = {'col1': [10, 20, 30, 40, 50],
        'col2': [100, 200, 300, 400, 500],
        'col3': ['A', 'B', 'C', 'D', 'E']}
df=pd.DataFrame(data)
df.set_index('col3',inplace=True)

In [ ]:
df.loc[:,['col1','col2']]

      col1  col2
col3
A       10   100
B       20   200
C       30   300
D       40   400
E       50   500

In [ ]:
df.loc[['A'],['col1','col1']]
df.loc[['A','B'],'col1':'col2']
df.loc['A']>30

col1    False
col2     True
Name: A, dtype: bool

In [ ]:
#iloc
df.iloc[0,1]
df.iloc[:,1]

col3
A    100
B    200
C    300
D    400
E    500
Name: col2, dtype: int64

#Drop  row

In [ ]:
df.drop('A',axis=0)#0 for row
df.drop(index=['A'])
df.drop('col1',axis=1)#1 for column
#drop columns by index
df.drop([0,1],axis=1)

NameError: name 'df' is not defined

### Sample

In [ ]:
df['col1'].sample(3,random_state=42)#Ramdom samples
df.sample(frac=0.2)#20% data
df.sample(frac=2,replace=True)# for frac>2 replace =True Upsampleing of data

###Query

In [ ]:
df.query("col1>30  and col2==100")

### Apply

In [ ]:
import numpy as np
df['col1'].apply(np.sqrt)
df['col2'].apply(lambda x:x*10)

### copy()

In [ ]:
df_copy=df.copy()
df_deep_copy=df.copy(deep=False)# any changes in df reflected in df_copy

### Pivot Tables

In [ ]:
foo=['one','one','one','one','two','two','two']
bar=['A','B','C','A','B','C']
zoo=['x','y','z','q','w','t']
baz=[1,2,3,4,5,6]
dict={'foo':foo,"bar":bar,"zoo","baz":baz}
import pandas as pd
df=pd.DataFrame(dict)
df.pivot(index='baz',columns='bar',values='baz')
#.pivot_table()
df.pivot_table(index='bar',aggfunc='sum')#Supports data aggregation

### Drop na

In [ ]:
df.dropna(inplace=True)
df_pivot=df.pivot(index='baz',columns='bar',values='baz')
df_pivot.plot(kind='line',xlabel='Alpha',ylabel='one/two')
df_pivot_bar=df.pivot[df.pivot.index.isin(['bar'])]
df_pivot_bar=df_pivot_bar.T
df_pivot_bar.plot(kind='bar')
# df_pivot_bar.rename(columns={})
df_pivot_bar.plot(kind='pie',y='A')

In [ ]:
#BoxPlot
df_pivot['A'].plot(kind='box')
#Multiple BoxPlot
df_pivot.plot(kind='box')
#Histogram
df_pivot['A','b'].plot(kind='hist')
#Scatter
df_pivot['A','B','C'].plot(kind='scatter',x='A','B')
#LinePlot
df_pivot.plot(kind='line')
plt.save_fig(".png")

### Plotly and cufflinks

In [ ]:
import pandas as pd
import cufflinks as cf
from IPython.display import display,HTML
cf.set_config_file(sharing='Public',theme='ggplot',offline=True)
cv.getThemes()

In [ ]:
df=pd.read_csv("population_total.csv")#Country,year,population
#LinePlot
df.dropna(inplace=True)
df_pivot=df.pivot(index='year',columns='country',values='population')
df_pivot=df_pivot[['United States','India','China','Indonesia','Brazil']]
df_pivot

In [ ]:
df_pivot.iplot(kind=line,xTittle='Years',yTittle='Population',title="Population")

In [ ]:
### BarPlot

In [ ]:
df_pivot_2020=df_pivot[df_pivot.index.isin([2020])]
df_pivot_2020=df_pivot_2020.T
df_pivot_2020.iplot(kind=bar)

In [ ]:
df_pivot_2020=df_pivot_2020.reset_index()

In [ ]:
#Pie Chart
df_pivot_2020.rename(columns={2020:'2020'},inplace=True)
df_pivot_2020.iplot(kind='pie',values='2020',labels='country')

In [ ]:
#box Plot
df_pivot['United States'].iplot(kind='box')

In [ ]:
#Histogram
df_pivot[['United States',"Indonesia"]].iplot(kind='hist')

In [ ]:
#Scatter Plot
df_pivot.scatter(kind='scatter',mode="markers")

### Aggregate functions

In [ ]:
import pandas as pd
df_cars=pd.read_csv("car_sales.csv")
df_cars=df_cars[['Manufacturer',"Sales_in_thousands",'Vehicle_type','Price_in_thousands','Engine_size',"Horsepower",'Fuel_capacity']]
df_cars.unique()

In [ ]:
df_cars.agg('sum')# mean count
df_cars.agg({"Sales_in_thousands";['sum','mean'],
             'Price_in_thousands':['sum','max']})
df_cars.aff(x=('Sales_in_thousands','sum'),
            y=('Price_in_thousands','sum'))
group_obj=df_cars.groupby('Vehicle_type').mean()
group_obj.groups
group_obj.get_group('Ford')

In [ ]:
#filter method
def filter_func(x):
  return x['Sales_in_thousands'].sum()>32
df_cars.group_by(['Manufacturer']).filter(filter_func)

### Merging and Concatenating

In [ ]:
import pandas as pd
df_moives=pd.read_csv("Imdbmovies.csv")
df_ratings=pd.read_csv("imdbratings.csv")
df_movies=df[['imdb_title_id','title','year','genre','country']]
df_ratings=df_ratings[['imdb_title_id','total_votes','mean_vote']]

In [ ]:
#concatenate vertically
df1=pd.DataFame({"id":['A','B','C','D'],
                 'age':[30,23,15,22]})
df2=pd.DataFame({"id":['E','F','G','H'],
                 df3=pd.DataFrame({'job':['Doctor','Statistician','Accountant','Developer']})
                 'age':[40,32,34,95]})
pd.concat([df1,df2],axis=0,ignore=True)
pd.concat([df1,df3],axis=1)

###Joins

In [ ]:
#Inner join have column things C D intersection
df1.merge(df2,one='id',how='inner')
#Full join Union
df1.merge(df2,one='id',how='outer')
#Exclusive full join without intersection
df1.merge(df1,one='id',how='outer',indicator=True)
#Left join A-B
df1.merge(df2,one='id',how='left')
#Exclusive a-b
df1.merge(df1,one='id',how='outer',indicator=True).query("_merge=='left_only'")

### Regular Expressions

In [ ]:
\d->Digit
\D-> nodigits
\w->word char
\s->whitespace
. ->anycharacter except new line character
\-> ignores special characters
^-> Begging of a string
$ ->End of the string
#Quantifiers
*->0 or more(greedy)
+ ->1 or more (greedy)
?-> 0 or 1
{3} exact
{n,} more than n characters
{3,4} range
( ) Group
[] matches characters in it
[^ ] macthes characters not in it
| or
\b -.word boundary
\1-reference

In [ ]:
import re
re.search(r'\d',text,flags=re.I)#Insensitive(case)
re.findall(r'\d',text)
#Date
re.findall(r'\d{2}-\d{2}-\d{4}',text)
#username identification
re.findall(r'[a-z0-9]{8,20}')

### Data Cleaning

In [ ]:
df=read_csv(".csv")
df.shape
df.dtypes

In [ ]:
#identify missing data
df.isnull()
#Dealing with it
#Remove the column or row (X)
df.drop("column",axis=0)# or axis=1
~df.is_null()
df.dropna(subset=['column or row name'])
df['column_name'].fillna(''.join(df['column'].mode()))
df.fillna(method='bfill or ffill')

In [ ]:
#Extraction of data
df["int column"].str.split(expand=True)[0].astype(int)
df['column'].str.extract('regularexp')

###Identifying outliers

In [ ]:
df['column'].plot(kind='hist',bins=10)
df['column'].value_counts(bins=10)#return bins #outliers
#With boxplot
df['column'].plot(kind='box',vert=False)
#overview descriptive statistics
#IQR=Q3-Q1
#Q1-1.5*TQR min (Q1=25% Q3=75%) min_boxplot
#Q3+1.5*TQR max max_boxplot
df['column'][~((df['column']>min_boxplot) & (df['column']<max_boxplot))]
#Use bar  same as

### Text normalization

In [ ]:
df['column'].str.lower() # or upper()/title()
df['column'].apply(lambda x:x.title())
# Remove blank spaces using strips
df['column'].str.strip()
# Replace strings with replace((r'[^\w\s]') or sub(r'[^\w\s]')
#Punctuation marks
df['column'].str.replace(r'[^\w\s]','',regex=True)#only Strings
df['column'].replace(1,2,regex=True)# any things
#using re
import re
df['column'].apply(lambda x:x.sub('[^\w\s]','',x))